# Generated by Django 6.0 on 2026-01-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_db',
            name='updated_at',
        ),
    ]
