# Generated by Django 6.0 on 2026-01-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_db_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_db',
            name='description',
        ),
    ]
